name: Deploy flowfuse from Local Chart to EKS

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'CI/CD prod'
        required: true
        default: 'latest'

jobs:
  override-config-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up AWS credentials from GitHub Secrets
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run a simple command
        run: echo "The self-hosted runner is working!"

      # Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      # Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Retrieve PostgreSQL Secrets from AWS SSM
        id: get-ssm-params
        run: |
          PG_NAME=$(aws ssm get-parameter --name "/smu/prod/db/ff-context/pg/name" --with-decryption --query "Parameter.Value" --output text)
          PG_HOST=$(aws ssm get-parameter --name "/smu/prod/db/ff-context/pg/host" --with-decryption --query "Parameter.Value" --output text)
          PG_PASS=$(aws ssm get-parameter --name "/smu/prod/db/ff-context/pg/pass" --with-decryption --query "Parameter.Value" --output text)
          PG_PORT=$(aws ssm get-parameter --name "/smu/prod/db/ff-context/pg/port" --with-decryption --query "Parameter.Value" --output text)
          PG_USER=$(aws ssm get-parameter --name "/smu/prod/db/ff-context/pg/user" --with-decryption --query "Parameter.Value" --output text)
          
          echo "::add-mask::$PG_PASS"  # Mask the password in logs
          
          echo "pg_name=$PG_NAME" >> $GITHUB_OUTPUT
          echo "pg_host=$PG_HOST" >> $GITHUB_OUTPUT
          echo "pg_pass=$PG_PASS" >> $GITHUB_OUTPUT
          echo "pg_port=$PG_PORT" >> $GITHUB_OUTPUT
          echo "pg_user=$PG_USER" >> $GITHUB_OUTPUT

      - name: Prepare Helm Values Override
        run: |
          cat > customization.yml << EOF
          postgresql:
            host: ${{ steps.get-ssm-params.outputs.pg_host }}
            port: ${{ steps.get-ssm-params.outputs.pg_port }}
            auth:
              username: ${{ steps.get-ssm-params.outputs.pg_user }}
              password: ${{ steps.get-ssm-params.outputs.pg_pass }}
              database: ${{ steps.get-ssm-params.outputs.pg_name }}
          EOF
          cat override-values.yaml  # Optional: for debugging, remove in production

      # Set up kubeconfig for EKS
      - name: Set up kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name smu-production-kubernetes

      # test access kubernetes
      - name: check ns
        run: |
          kubectl get ns

      # Step 5: Install/Upgrade Flowfuse using Helm
      #- name: Helm upgrade/installation
      #  run: |
      #    helm repo add flowfuse https://flowfuse.github.io/flowforge
      #    helm repo update
      #    helm upgrade --atomic --install --timeout 10m flowfuse flowfuse/flowforge -f customization.yml -n flowfuse

      # Optionally, check the status of the Helm release
      #- name: Check Helm release status
      #  run: |
      #    helm status flowfuse -n flowfuse
